language: php
php:
  - 5.6

sudo: false

before_install:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update

before_script: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose